"Smarts get you far. But hard work gets you farther." - ThePrimeagen
"In order to attain the impossible, one must attempt the absurd." - Miguel de Cervantes
"My tomu neříkáme věda, my tomu říkáme řemeslo." - Ing. Tomáš Klinkovský
"You would worry a lot less what other people think of you, if you realised how infrequently they do." - Austin Wintory's dad
"Stress is your inability to controll your body and your mind." - Sadghuru
"Perfect is usually someone else's idea of what you should be." - James Pumphrey
"The world will not deliver to you what you want, the world will deliver to you what you need." - Dr. K
"Best way to run from an unsolvable problem is to solve something else." - Dr. K
"Simplicity is the ultimate sophistication" - Leonardo da Vinci (supposedly)
"The more that you think your mind is you the more mentally ill you get." - Dr. K
"I'm all over the place. I'm just like... Hey, if it has to do with plant sex, put it in my mouth." - Michael Stevens
"I think that self control is a trainable skill. And it is a byproduct of flourishing." - Dr. Richard Davidson
"Everything seemed easy, until suddenly it wasn't." - Tris, No Boilerplate
"When you have reached the opposite shore, you do not carry the raft on your back, but leave it behind." - Alan Watts
"If a cluttered desk is a sign of a cluttered mind, we can't help wondering what an empty desk indicates." - Albert Einstein (supposedly)
"The reason that you're seeing all this bad stuff on the news is because bad stuff is newsworthy." - Andy Weir
"Never trust a thought that occurs to you indoors." - Friedrich Nietzsche
