foreground {{foreground}}
background {{background}}
cursor {{cursor}}
selection_foreground {{background}}
selection_background {{foreground}}

color0 {{color0}}
color1 {{color1 | lighten(0.35)}}
color2 {{color2 | lighten(0.35)}}
color3 {{color3 | lighten(0.35)}}
color4 {{color4 | lighten(0.35)}}
color5 {{color5 | lighten(0.35)}}
color6 {{color6 | lighten(0.35)}}
color7 {{color7}}
color8 {{color8}}
color9 {{color9 | lighten(0.35)}}
color10 {{color10 | lighten(0.35)}}
color11 {{color11 | lighten(0.35)}}
color12 {{color12 | lighten(0.35)}}
color13 {{color13 | lighten(0.35)}}
color14 {{color14 | lighten(0.35)}}
color15 {{color15}}
